version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: los-postgres
    environment:
      POSTGRES_USER: los
      POSTGRES_PASSWORD: los
      POSTGRES_DB: los
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    container_name: los-redpanda
    command:
      - redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 \
        --check=false --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092 \
        --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda:/var/lib/redpanda/data

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: los-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: los-keycloak
    command: start-dev --http-port=8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  pgdata: {}
  redpanda: {}
  minio: {}


