steps:
  # Build Docker images for all services
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-gateway'
    args:
      - 'build'
      - '-f'
      - 'gateway/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/gateway:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/gateway:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-application'
    args:
      - 'build'
      - '-f'
      - 'services/application/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/application:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/application:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-customer-kyc'
    args:
      - 'build'
      - '-f'
      - 'services/customer-kyc/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/customer-kyc:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/customer-kyc:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-document'
    args:
      - 'build'
      - '-f'
      - 'services/document/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/document:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/document:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-masters'
    args:
      - 'build'
      - '-f'
      - 'services/masters/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/masters:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/masters:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-underwriting'
    args:
      - 'build'
      - '-f'
      - 'services/underwriting/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/underwriting:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/underwriting:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-sanction-offer'
    args:
      - 'build'
      - '-f'
      - 'services/sanction-offer/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/sanction-offer:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/sanction-offer:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-payments'
    args:
      - 'build'
      - '-f'
      - 'services/payments/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/payments:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/payments:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-disbursement'
    args:
      - 'build'
      - '-f'
      - 'services/disbursement/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/disbursement:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/disbursement:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-orchestrator'
    args:
      - 'build'
      - '-f'
      - 'services/orchestrator/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/orchestrator:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/orchestrator:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-notifications'
    args:
      - 'build'
      - '-f'
      - 'services/notifications/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/notifications:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/notifications:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-audit'
    args:
      - 'build'
      - '-f'
      - 'services/audit/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/audit:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/audit:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-bureau'
    args:
      - 'build'
      - '-f'
      - 'services/bureau/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/bureau:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/bureau:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-verification'
    args:
      - 'build'
      - '-f'
      - 'services/verification/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/verification:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/verification:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-reporting'
    args:
      - 'build'
      - '-f'
      - 'reporting/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/reporting:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/reporting:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-integration-hub'
    args:
      - 'build'
      - '-f'
      - 'services/integration-hub/Dockerfile'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/integration-hub:${SHORT_SHA}'
      - '-t'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/integration-hub:latest'
      - '.'

  # Push images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    args:
      - 'push'
      - '--all-tags'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/gateway'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/application'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/customer-kyc'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/document'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/masters'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/underwriting'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/sanction-offer'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/payments'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/disbursement'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/orchestrator'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/notifications'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/audit'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/bureau'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/verification'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/reporting'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/integration-hub'
    waitFor: ['build-gateway', 'build-application', 'build-customer-kyc', 'build-document', 'build-masters', 'build-underwriting', 'build-sanction-offer', 'build-payments', 'build-disbursement', 'build-orchestrator', 'build-notifications', 'build-audit', 'build-bureau', 'build-verification', 'build-reporting', 'build-integration-hub']

substitutions:
  _GCP_REGION: 'us-central1'
  _ARTIFACT_REGISTRY: 'los-images'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  timeout: '3600s'

images:
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/gateway:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/gateway:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/application:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/application:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/customer-kyc:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/customer-kyc:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/document:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/document:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/masters:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/masters:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/underwriting:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/underwriting:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/sanction-offer:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/sanction-offer:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/payments:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/payments:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/disbursement:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/disbursement:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/orchestrator:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/orchestrator:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/notifications:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/notifications:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/audit:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/audit:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/bureau:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/bureau:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/verification:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/verification:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/reporting:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/reporting:latest'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/integration-hub:${SHORT_SHA}'
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/integration-hub:latest'

