name: Docker Build

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # Use github.repository_owner to get the owner/organization
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build-services:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        service:
          - name: gateway
            dockerfile: gateway/Dockerfile
            port: 3000
          - name: application
            dockerfile: services/application/Dockerfile
            port: 3001
          - name: customer-kyc
            dockerfile: services/customer-kyc/Dockerfile
            port: 3002
          - name: document
            dockerfile: services/document/Dockerfile
            port: 3003
          - name: masters
            dockerfile: services/masters/Dockerfile
            port: 3004
          - name: underwriting
            dockerfile: services/underwriting/Dockerfile
            port: 3006
          - name: sanction-offer
            dockerfile: services/sanction-offer/Dockerfile
            port: 3007
          - name: payments
            dockerfile: services/payments/Dockerfile
            port: 3008
          - name: disbursement
            dockerfile: services/disbursement/Dockerfile
            port: 3009
          - name: orchestrator
            dockerfile: services/orchestrator/Dockerfile
            port: 3010
          - name: notifications
            dockerfile: services/notifications/Dockerfile
            port: 3011
          - name: audit
            dockerfile: services/audit/Dockerfile
            port: 3012
          - name: bureau
            dockerfile: services/bureau/Dockerfile
            port: 3013
          - name: verification
            dockerfile: services/verification/Dockerfile
            port: 3014
          - name: reporting
            dockerfile: reporting/Dockerfile
            port: 3015
          - name: integration-hub
            dockerfile: services/integration-hub/Dockerfile
            port: 3020

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-${{ matrix.service.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: build-services
    if: always()
    
    steps:
      - name: Summary
        run: |
          echo "## Docker Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "All Docker images have been built successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Services built:" >> $GITHUB_STEP_SUMMARY
          echo "- Gateway" >> $GITHUB_STEP_SUMMARY
          echo "- Application" >> $GITHUB_STEP_SUMMARY
          echo "- Customer KYC" >> $GITHUB_STEP_SUMMARY
          echo "- Document" >> $GITHUB_STEP_SUMMARY
          echo "- Masters" >> $GITHUB_STEP_SUMMARY
          echo "- Underwriting" >> $GITHUB_STEP_SUMMARY
          echo "- Sanction Offer" >> $GITHUB_STEP_SUMMARY
          echo "- Payments" >> $GITHUB_STEP_SUMMARY
          echo "- Disbursement" >> $GITHUB_STEP_SUMMARY
          echo "- Orchestrator" >> $GITHUB_STEP_SUMMARY
          echo "- Notifications" >> $GITHUB_STEP_SUMMARY
          echo "- Audit" >> $GITHUB_STEP_SUMMARY
          echo "- Bureau" >> $GITHUB_STEP_SUMMARY
          echo "- Verification" >> $GITHUB_STEP_SUMMARY
          echo "- Reporting" >> $GITHUB_STEP_SUMMARY
          echo "- Integration Hub" >> $GITHUB_STEP_SUMMARY

